version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:9.0
    volumes:
      - ..:/workspaces/mymon3y:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: