version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:9.0
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    volumes:
      - sqlserver-data:/var/opt/mssql
    
volumes:
  sqlserver-data: